name: Update Footer

on:
  push:
    branches:
      - main  # Đổi thành tên branch bạn dùng

jobs:
  update-footer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update footer.html
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          DATE=$(date '+%Y-%m-%d %H:%M:%S')
          YEAR=$(date '+%Y')
          sed -i "s|<p>.*</p>|<p>© $YEAR Github. Last updated: $DATE — Commit: $COMMIT_HASH</p>|" components/footer.html

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add components/footer.html
          git commit -m "chore: update footer [skip ci]" || echo "No changes"
          git push
